# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 00:16
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('nodeID', models.PositiveIntegerField(verbose_name='Tree Node ID')),
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=64, verbose_name='Brand')),
                ('type', models.CharField(max_length=64, verbose_name='Type')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('unit', models.CharField(choices=[('ML', 'Milliliters'), ('L', 'Liters'), ('KG', 'Kilograms'), ('G', 'Grams'), ('Piece', 'Pieces')], max_length=8, verbose_name='Unit')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=64, verbose_name='City Name')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('districtID', models.AutoField(primary_key=True, serialize=False)),
                ('cityID', models.PositiveIntegerField(verbose_name='City ID')),
                ('districtName', models.CharField(max_length=64, verbose_name='District Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('productGroupID', models.AutoField(primary_key=True, serialize=False)),
                ('productGroupName', models.CharField(max_length=128, verbose_name='Product Group Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentID', models.PositiveIntegerField(verbose_name='Group ID')),
                ('childID', models.PositiveIntegerField(verbose_name='Product ID')),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('retailerName', models.CharField(max_length=256, verbose_name='Retailer Name')),
                ('retailerTypeID', models.PositiveIntegerField(verbose_name='Retailer Type')),
                ('retailerID', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=512, verbose_name='Address')),
                ('geoLocation', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('cityID', models.PositiveIntegerField(editable=False, null=True)),
                ('districtID', models.PositiveIntegerField(editable=False, null=True)),
                ('zipCode', models.CharField(editable=False, max_length=8, null=True)),
            ],
            managers=[
                ('gis', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RetailerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.PositiveIntegerField(verbose_name='Base Product')),
                ('retailerID', models.PositiveIntegerField(verbose_name='Retailer')),
                ('unitPrice', models.PositiveIntegerField(verbose_name='Unit Price(₺)')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerType',
            fields=[
                ('retailerTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('retailerTypeName', models.CharField(max_length=128, verbose_name='Retailer Type Name')),
            ],
        ),
    ]
