# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailerproduct',
            name='productID',
            field=models.PositiveIntegerField(choices=[(1, 'Sütaş Süt 1L')], verbose_name='Base Product'),
        ),
    ]
