# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 00:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0002_auto_20170204_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='lastEdited',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 4, 0, 20, 42, 589218, tzinfo=utc), verbose_name='Last Edited'),
        ),
    ]
