# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0003_retailer_lastedited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='lastEdited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Edited'),
        ),
    ]
