# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0005_remove_retailer_lastedited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductNode',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='parentGroupID',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Parent Group Name'),
        ),
        migrations.AlterField(
            model_name='retailerproduct',
            name='productID',
            field=models.PositiveIntegerField(verbose_name='Base Product'),
        ),
    ]
