# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0006_auto_20170206_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='lastEditTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 6, 23, 28, 6, 59256, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='retailerproduct',
            name='lastEditTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 6, 23, 28, 6, 60955, tzinfo=utc), editable=False),
        ),
    ]
