# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0007_auto_20170206_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='lastEditTime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='retailerproduct',
            name='lastEditTime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
