# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0008_auto_20170206_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='lastEditTime',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AlterField(
            model_name='retailerproduct',
            name='lastEditTime',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
