# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0009_auto_20170206_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='parentGroupID',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Parent Group Name'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='lastEditTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='retailerproduct',
            name='lastEditTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
