# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0010_auto_20170206_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileID', models.AutoField(primary_key=True, serialize=False)),
                ('profileName', models.CharField(max_length=64, verbose_name='Profile Name')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('listID', models.AutoField(primary_key=True, serialize=False)),
                ('profileID', models.PositiveIntegerField(verbose_name='Profile ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
                ('isCompleted', models.BooleanField(default=False, verbose_name='Completed?')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingListItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listID', models.PositiveIntegerField(verbose_name='List ID')),
                ('profileID', models.PositiveIntegerField(verbose_name='Profile ID')),
                ('userID', models.PositiveIntegerField(verbose_name='User ID')),
                ('productID', models.PositiveIntegerField(verbose_name='Product ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100, verbose_name='User Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('firstName', models.CharField(max_length=64, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=64, verbose_name='Last Name')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileID', models.PositiveIntegerField(verbose_name='Profile ID')),
                ('userID', models.PositiveIntegerField(verbose_name='User ID')),
            ],
        ),
        migrations.AlterField(
            model_name='retailer',
            name='geoLocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, geography=True, null=True, srid=4326),
        ),
    ]
