# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0011_auto_20170212_2350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingListItems',
            new_name='ShoppingListItem',
        ),
    ]
