# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0012_auto_20170212_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='profileID',
        ),
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='userID',
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='profileID',
            field=models.PositiveIntegerField(verbose_name='Profile Name'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='listID',
            field=models.PositiveIntegerField(verbose_name='List Name'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='productID',
            field=models.PositiveIntegerField(verbose_name='Product Name'),
        ),
    ]
