# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0013_auto_20170213_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='parentGroupID',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='childConnectionID',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Child Connection ID'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='isLeaf',
            field=models.BooleanField(default=False, verbose_name='Is this a leaf node?'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='isRoot',
            field=models.BooleanField(default=False, verbose_name='Is this a root node?'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='parentConnectionID',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Parent Connection ID'),
        ),
        migrations.AlterField(
            model_name='retailer',
            name='retailerTypeID',
            field=models.PositiveIntegerField(choices=[(2, 'Shopping Center'), (1, 'Supermarket')], verbose_name='Retailer Type'),
        ),
        migrations.AlterField(
            model_name='retailerproduct',
            name='productID',
            field=models.PositiveIntegerField(choices=[(1, 'Sütaş Süt 1L'), (2, 'Pınar Yoğurt 500G'), (3, 'İçim Beyaz Peynir 250G'), (4, 'Torku Banada 1Piece'), (5, 'Ülker Sütlü Çikolata 1Piece')], verbose_name='Base Product'),
        ),
        migrations.AlterField(
            model_name='retailerproduct',
            name='retailerID',
            field=models.PositiveIntegerField(choices=[(10, 'Atlantis AVM'), (11, 'Kentpark AVM'), (12, 'Gordion AVM'), (13, 'Panora AVM'), (14, 'Kızılay AVM'), (15, 'Cepa AVM'), (8, 'Arcadium AVM'), (16, 'Armada AVM'), (9, 'Ankamall AVM'), (19, 'Next Level'), (22, 'Yunus Market'), (25, 'Bakkal')], verbose_name='Retailer'),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='profileID',
            field=models.PositiveIntegerField(choices=[(1, 'Test Profile 1'), (2, 'Test Profile 2'), (3, 'Test Profile 3')], verbose_name='Profile Name'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='listID',
            field=models.PositiveIntegerField(choices=[(2, "dyanikoglu:Test Profile 1's Shopping List"), (3, "tozyer:Test Profile 2's Shopping List"), (4, "tozyer:Test Profile 3's Shopping List")], verbose_name='List Name'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='productID',
            field=models.PositiveIntegerField(choices=[(1, 'Sütaş Süt 1L'), (2, 'Pınar Yoğurt 500G'), (3, 'İçim Beyaz Peynir 250G'), (4, 'Torku Banada 1Piece'), (5, 'Ülker Sütlü Çikolata 1Piece')], verbose_name='Product Name'),
        ),
    ]
