# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0014_auto_20170227_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeEdge',
            fields=[
                ('edgeID', models.AutoField(primary_key=True, serialize=False)),
                ('parentNodeID', models.PositiveIntegerField(blank=True, null=True, verbose_name='Parent Node ID')),
                ('childNodeID', models.PositiveIntegerField(blank=True, null=True, verbose_name='Child Node ID')),
                ('isEdgeBetweenGroups', models.BooleanField(default=True, verbose_name='Is this an edge between 2 groups?')),
            ],
        ),
        migrations.RemoveField(
            model_name='baseproduct',
            name='nodeID',
        ),
    ]
