# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0015_auto_20170227_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeedge',
            name='parentNodeID',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parent Node ID'),
        ),
    ]
