# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0016_auto_20170227_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='parentConnectionID',
            field=models.IntegerField(blank=True, null=True, verbose_name='Parent Connection ID'),
        ),
        migrations.AlterField(
            model_name='treeedge',
            name='parentNodeID',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Parent Node ID'),
        ),
    ]
