# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0017_auto_20170227_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeedge',
            name='childNodeID',
            field=models.PositiveIntegerField(null=True, verbose_name='Child Node ID'),
        ),
        migrations.AlterField(
            model_name='treeedge',
            name='parentNodeID',
            field=models.PositiveIntegerField(choices=[(1, 'Fruits & Vegetables'), (2, 'Meat & Fish'), (3, 'Milk & Breakfast'), (4, 'Nutrition & Confectionary'), (5, 'Beverage'), (6, 'Cleaning Products'), (7, 'Cosmetic'), (8, 'Baby Products & Toys'), (9, 'Furnitures & Other House Products')], null=True, verbose_name='Parent Node ID'),
        ),
    ]
