# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0021_auto_20170227_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailer',
            name='retailerTypeID',
        ),
        migrations.AddField(
            model_name='retailer',
            name='retailerType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.RetailerType'),
        ),
        migrations.AlterField(
            model_name='retailerproduct',
            name='productID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisModule.BaseProduct'),
        ),
        migrations.AlterField(
            model_name='retailerproduct',
            name='retailerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisModule.Retailer'),
        ),
    ]
