# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0022_auto_20170227_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailerproduct',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='retailerproduct',
            name='retailerID',
        ),
        migrations.AddField(
            model_name='retailerproduct',
            name='baseProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.BaseProduct'),
        ),
        migrations.AddField(
            model_name='retailerproduct',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.Retailer'),
        ),
    ]
