# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import gisModule.models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0025_auto_20170227_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treeedge',
            name='childNodeID',
            field=models.ForeignKey(null=True, on_delete=gisModule.models.BaseProduct, related_name='Child', to='gisModule.ProductGroup'),
        ),
    ]
