# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0026_auto_20170227_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treeedge',
            old_name='parentNodeID',
            new_name='parentNode',
        ),
        migrations.RemoveField(
            model_name='treeedge',
            name='childNodeID',
        ),
        migrations.AddField(
            model_name='treeedge',
            name='childGroupNode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.ProductGroup'),
        ),
        migrations.AddField(
            model_name='treeedge',
            name='childProductNode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.BaseProduct'),
        ),
    ]
