# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0027_auto_20170227_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeConnection',
            fields=[
                ('edgeID', models.AutoField(primary_key=True, serialize=False)),
                ('isEdgeBetweenGroups', models.BooleanField(default=True, verbose_name='Is this an edge between 2 groups?')),
                ('childGroupNode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChildGroupNode', to='gisModule.ProductGroup')),
                ('childProductNode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChildProductNode', to='gisModule.BaseProduct')),
                ('parentNode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParentNode', to='gisModule.ProductGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='treeedge',
            name='childGroupNode',
        ),
        migrations.RemoveField(
            model_name='treeedge',
            name='childProductNode',
        ),
        migrations.RemoveField(
            model_name='treeedge',
            name='parentNode',
        ),
        migrations.DeleteModel(
            name='TreeEdge',
        ),
    ]
