# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0028_auto_20170227_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeconnection',
            name='childProductNode',
        ),
    ]
