# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0029_remove_treeconnection_childproductnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeEdge',
            fields=[
                ('edgeID', models.AutoField(primary_key=True, serialize=False)),
                ('isEdgeBetweenGroups', models.BooleanField(default=True, verbose_name='Is this an edge between 2 groups?')),
            ],
        ),
        migrations.RemoveField(
            model_name='treeconnection',
            name='childGroupNode',
        ),
        migrations.RemoveField(
            model_name='treeconnection',
            name='parentNode',
        ),
        migrations.DeleteModel(
            name='TreeConnection',
        ),
    ]
