# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0030_auto_20170227_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeedge',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.ProductGroup'),
        ),
    ]
