# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0031_treeedge_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeedge',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Child', to='gisModule.ProductGroup'),
        ),
        migrations.AlterField(
            model_name='treeedge',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Parent', to='gisModule.ProductGroup'),
        ),
    ]
