# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0034_auto_20170227_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='treeedge',
            name='child2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductChild', to='gisModule.BaseProduct'),
        ),
        migrations.AlterField(
            model_name='treeedge',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GroupChild', to='gisModule.ProductGroup'),
        ),
        migrations.AlterField(
            model_name='treeedge',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GroupParent', to='gisModule.ProductGroup'),
        ),
    ]
