# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0036_treeedge_isgroupedge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treeedge',
            old_name='child',
            new_name='groupChild',
        ),
        migrations.RenameField(
            model_name='treeedge',
            old_name='child2',
            new_name='productChild',
        ),
    ]
