# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0037_auto_20170227_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='childConnection',
            field=models.IntegerField(null=True, verbose_name='Child Connection ID'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='parentConnection',
            field=models.IntegerField(null=True, verbose_name='Parent Connection ID'),
        ),
    ]
