# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0038_auto_20170227_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='childConnection',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='parentConnection',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='childConnectionID',
            field=models.IntegerField(default=None, editable=False, null=True, verbose_name='Child Connection ID'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='parentConnectionID',
            field=models.IntegerField(default=None, editable=False, null=True, verbose_name='Parent Connection ID'),
        ),
    ]
