# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0040_auto_20170227_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='parentConnectionID',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Parent Connection ID'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='childConnectionID',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Child Connection ID'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='parentConnectionID',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Parent Connection ID'),
        ),
        migrations.AlterField(
            model_name='treeedge',
            name='groupChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GroupChild', to='gisModule.ProductGroup'),
        ),
        migrations.AlterField(
            model_name='treeedge',
            name='productChild',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductChild', to='gisModule.BaseProduct'),
        ),
    ]
