# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0041_auto_20170227_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='childConnectionID',
        ),
        migrations.AddField(
            model_name='productgroup',
            name='childConnectionIDs',
            field=models.CharField(blank=True, editable=False, max_length=1024, null=True, verbose_name='Child Connection ID List'),
        ),
    ]
