# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0042_auto_20170227_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgroup',
            name='isLeaf',
        ),
    ]
