# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0043_remove_productgroup_isleaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='type',
            field=models.CharField(blank=True, max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='unit',
            field=models.CharField(choices=[('ML', 'Milliliters'), ('L', 'Liters'), ('KG', 'Kilograms'), ('G', 'Grams'), (' Units', 'Units')], max_length=8, verbose_name='Unit'),
        ),
    ]
