# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0044_auto_20170228_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='isLeaf',
            field=models.BooleanField(default=False, verbose_name='Is this a leaf node?'),
        ),
        migrations.AlterField(
            model_name='baseproduct',
            name='unit',
            field=models.CharField(choices=[('ML', 'Milliliters'), ('L', 'Liters'), ('KG', 'Kilograms'), ('G', 'Grams'), (' Units', 'Units'), (' Cans', 'Cans')], max_length=8, verbose_name='Unit'),
        ),
    ]
