# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0045_auto_20170228_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=512, verbose_name='Password'),
        ),
    ]
