# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-03 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0046_auto_20170303_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='lastUpdated',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='profileID',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='listName',
            field=models.CharField(default='Shopping List', max_length=64, verbose_name='List Name'),
        ),
    ]
