# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-03 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0047_auto_20170303_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoppingList', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.ShoppingList')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
