# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-03 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0048_auto_20170303_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistitem',
            name='listID',
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.ShoppingList'),
        ),
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.BaseProduct'),
        ),
    ]
