# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-03 23:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0049_auto_20170303_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglistitem',
            old_name='productID',
            new_name='product',
        ),
    ]
