# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-04 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0051_shoppinglistitem_addedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershoppinglist',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Is active?'),
        ),
    ]
