# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-06 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0052_usershoppinglist_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppinglist',
            old_name='creationDate',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='usershoppinglist',
            name='isActive',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activeList',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='gisModule.ShoppingList'),
        ),
    ]
