# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-06 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0053_auto_20170306_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
