# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 10:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0054_auto_20170306_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedAddress',
            fields=[
                ('name', models.CharField(max_length=256, verbose_name='Address Name')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=512, verbose_name='Address')),
                ('geoLocation', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, geography=True, null=True, srid=4326)),
                ('zipcode', models.CharField(editable=False, max_length=8, null=True)),
                ('last_edit_time', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.City')),
                ('district', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.District')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gisModule.User')),
            ],
            managers=[
                ('gis', django.db.models.manager.Manager()),
            ],
        ),
    ]
