# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0055_usersavedaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_factor', models.BooleanField(verbose_name='Money Factor')),
                ('dist_factor', models.BooleanField(verbose_name='Distance Factor')),
                ('market_factor', models.BooleanField(verbose_name='Market Factor')),
                ('time_factor', models.BooleanField(verbose_name='Time Factor')),
                ('user', models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='gisModule.User')),
            ],
        ),
    ]
