# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0057_userpreferences_search_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreferences',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='gisModule.UserPreferences'),
        ),
    ]
