# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gisModule', '0059_auto_20170424_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='route_end_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EndAddress', to='gisModule.UserSavedAddress'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='route_start_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='StartAddress', to='gisModule.UserSavedAddress'),
        ),
    ]
